version: '0.7'

services:

  db:
    image: postgres:16rc1-alpine
    env_file:
      - sec.env  
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U webdb"]
      interval: 6s
      timeout: 5s
      retries: 5
  
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file:
      - sec.env
    depends_on:
      - db
    ports:
    - "3000:3000"
    restart: on-failure
    stdin_open: true
    tty: true
  
  
  
  
volumes:
  db_data:
